name: OpenAPI
on:
  pull_request:
    

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: blake-mealey/openapi-review-action@v1
        with:
          spec-paths: poweroffice-go-openapi.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}