name: OpenAPI
on:
  pull_request:
    

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: blake-mealey/openapi-review-action@v1
        with:
          spec-paths: poweroffice-go-openapi.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}