name: OpenAPI
on:
  pull_request:
    

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: blake-mealey/openapi-review-action@v1
        with:
          spec-paths: poweroffice-go-openapi.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}